In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
a=np.array([1,2,3,4,4])
a

array([1, 2, 3, 4, 4])

In [5]:
a[3]

np.int64(4)

In [6]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [7]:
w=np.array([[1,3,4],
          [3,4,5],
          [6,7,8]])
w

array([[1, 3, 4],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
w[1,2]

np.int64(5)

In [9]:
np.random.rand(5,2)

array([[0.9390744 , 0.93508407],
       [0.65805824, 0.75382523],
       [0.86816666, 0.24597923],
       [0.58309943, 0.17736589],
       [0.97522287, 0.92139896]])

In [11]:
num=np.arange(5)
num

array([0, 1, 2, 3, 4])

In [12]:
num *2

array([0, 2, 4, 6, 8])

In [13]:
10 + (num *3)

array([10, 13, 16, 19, 22])

In [14]:
num >= 3

array([False, False, False,  True,  True])

In [15]:
num.max()

np.int64(4)

In [16]:
num.mean()

np.float64(2.0)

vector & matrix

In [4]:
u=np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [5]:
v=np.array([1,0,0,2])
v

array([1, 0, 0, 2])

In [6]:
u+v

array([3, 4, 5, 8])

In [7]:
def vector_vector_multiply(u,v):
    assert u.shape[0] == v.shape[0]
    
    n=u.shape[0]
    result=0.0

    for i in range(n):
        result += u[i]*v[i]

    return result

In [8]:
vector_vector_multiply(u,v)

np.float64(14.0)

In [9]:
m=np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
m

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [11]:
def matrix_vector_multiply(m,v):
    assert m.shape[1] == v.shape[0]
    num_rows=m.shape[0]
    result=np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiply(m[i],v)

    return result

In [12]:
matrix_vector_multiply(m,v)

array([14.,  5.,  5.])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])