In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
a=np.array([1,2,3,4,4])
a

array([1, 2, 3, 4, 4])

In [5]:
a[3]

np.int64(4)

In [6]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [7]:
w=np.array([[1,3,4],
          [3,4,5],
          [6,7,8]])
w

array([[1, 3, 4],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
w[1,2]

np.int64(5)

In [9]:
np.random.rand(5,2)

array([[0.9390744 , 0.93508407],
       [0.65805824, 0.75382523],
       [0.86816666, 0.24597923],
       [0.58309943, 0.17736589],
       [0.97522287, 0.92139896]])

In [11]:
num=np.arange(5)
num

array([0, 1, 2, 3, 4])

In [12]:
num *2

array([0, 2, 4, 6, 8])

In [13]:
10 + (num *3)

array([10, 13, 16, 19, 22])

In [14]:
num >= 3

array([False, False, False,  True,  True])

In [15]:
num.max()

np.int64(4)

In [16]:
num.mean()

np.float64(2.0)